# Generated by Django 5.0.4 on 2026-04-10 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日付')),
                ('clock_in', models.TimeField(blank=True, null=True, verbose_name='出勤時刻')),
                ('clock_out', models.TimeField(blank=True, null=True, verbose_name='退勤時刻')),
                ('break_minutes', models.PositiveIntegerField(default=60, verbose_name='休憩時間（分）')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('confirmed', '確定'), ('modified', '修正済')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'verbose_name': '勤怠記録',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceModRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_clock_in', models.TimeField(verbose_name='修正後出勤時刻')),
                ('requested_clock_out', models.TimeField(verbose_name='修正後退勤時刻')),
                ('reason', models.TextField(verbose_name='修正理由')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済'), ('rejected', '却下')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_requests_sent', to='employees.employee')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_requests_received', to='employees.employee')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_requests', to='attendance.attendancerecord')),
            ],
            options={
                'verbose_name': '打刻修正申請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='件番')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employees.employee', verbose_name='管理者')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.project'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'date')},
        ),
    ]
