# Generated by Django 5.0.4 on 2026-04-16 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_multi_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceprojectrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
