# Generated by Django 5.0.4 on 2026-04-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendanceprojectrecord_id'),
        ('attendance', '0003_workrule'),
    ]

    operations = [
    ]
