# Generated by Django 5.0.4 on 2026-04-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_merge_20260416_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
