# Generated by Django 5.0.4 on 2026-04-24 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_project_sub_managers'),
        ('employees', '0005_softdelete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employees.employee', verbose_name='主管理者'),
        ),
    ]
