# Generated by Django 5.0.4 on 2026-04-24 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_project_manager_sub_managers'),
        ('employees', '0005_softdelete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employees.employee', verbose_name='主管理者'),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_managers',
            field=models.ManyToManyField(blank=True, related_name='sub_managed_projects', to='employees.employee', verbose_name='従管理者'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='削除者'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='削除済み'),
        ),
    ]
