# Generated by Django 5.0.4 on 2026-04-10 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBOGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(verbose_name='年度')),
                ('period', models.CharField(choices=[('first_half', '上期'), ('second_half', '下期')], max_length=20, verbose_name='期')),
                ('title', models.CharField(max_length=200, verbose_name='目標タイトル')),
                ('target_level', models.TextField(blank=True, verbose_name='達成水準')),
                ('weight', models.PositiveIntegerField(default=100, verbose_name='ウェイト（%）')),
                ('self_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='自己評価')),
                ('manager_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='上司評価')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済'), ('approved', '承認済'), ('evaluated', '評価済')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mbo_goals', to='employees.employee')),
            ],
            options={
                'verbose_name': 'MBO目標',
                'ordering': ['-year', 'period'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(verbose_name='報告日')),
                ('content', models.TextField(verbose_name='内容')),
                ('ai_suggestion', models.TextField(blank=True, verbose_name='AI提案')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='employees.employee')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('employee', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='MBOReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(verbose_name='対象月（月初日を格納）')),
                ('action_content', models.TextField(blank=True, verbose_name='行動内容')),
                ('result', models.TextField(blank=True, verbose_name='結果・考察')),
                ('manager_comment', models.TextField(blank=True, verbose_name='上司コメント')),
                ('ai_suggestion', models.TextField(blank=True, verbose_name='AI提案')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済'), ('commented', 'コメント済')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mbo.mbogoal')),
            ],
            options={
                'verbose_name': 'MBO月間報告',
                'ordering': ['-month'],
                'unique_together': {('goal', 'month')},
            },
        ),
    ]
