# Generated by Django 5.0.4 on 2026-04-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='common_audi_app_lab_0fa6cc_idx',
            old_name='auditlog_model_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='common_audi_user_id_740557_idx',
            old_name='auditlog_user_ts_idx',
        ),
    ]
