# Generated by Django 5.0.4 on 2026-04-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_softdelete_fields'),
        ('stress_check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stresscheckresponse',
            name='unique_stress_check_response',
        ),
        migrations.AlterUniqueTogether(
            name='stresscheckresponse',
            unique_together={('period', 'employee')},
        ),
    ]
