# Generated by Django 5.0.4 on 2026-04-10 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('attendance_mod', '打刻修正申請'), ('leave_request', '休暇申請'), ('mbo_feedback', 'MBOフィードバック'), ('expense_request', '経費申請'), ('overtime_alert', '残業時間アラート'), ('leave_alert', '有給残日数アラート'), ('skill_expiry', '資格有効期限アラート'), ('system', 'システム通知')], max_length=30)),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('related_url', models.CharField(blank=True, max_length=500, verbose_name='関連URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
