# Generated by Django 5.0.4 on 2026-04-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_softdelete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('attendance_mod', '打刻修正申請'), ('leave_request', '休暇申請'), ('mbo_feedback', 'MBOフィードバック'), ('expense_request', '経費申請'), ('overtime_alert', '残業時間アラート（月）'), ('overtime_annual_alert', '残業時間アラート（年）'), ('leave_alert', '有給残日数アラート'), ('skill_expiry', '資格有効期限アラート'), ('system', 'システム通知'), ('stress_check', 'ストレスチェック'), ('onboarding', 'オンボーディング')], max_length=30),
        ),
    ]
