# Generated by Django 5.0.4 on 2026-04-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_softdelete_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quizanswer',
            name='unique_attempt_question',
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
