# Generated by Django 5.0.4 on 2026-04-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intra', '0002_article_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='本文'),
        ),
    ]
