# Generated by Django 5.0.4 on 2026-04-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', '社員'), ('manager', '管理職'), ('hr', '人事'), ('labor', '労務'), ('accounting', '経理'), ('customer', '顧客'), ('admin', 'システム管理者')], default='employee', max_length=20),
        ),
    ]
