# Generated by Django 5.0.4 on 2026-04-10 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=20, unique=True, verbose_name='社員番号')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('last_name_kana', models.CharField(max_length=50, verbose_name='姓（カナ）')),
                ('first_name_kana', models.CharField(max_length=50, verbose_name='名（カナ）')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=10, verbose_name='性別')),
                ('hire_date', models.DateField(verbose_name='入社日')),
                ('retire_date', models.DateField(blank=True, null=True, verbose_name='退職日')),
                ('department', models.CharField(max_length=100, verbose_name='部署')),
                ('position', models.CharField(max_length=100, verbose_name='役職')),
                ('grade', models.PositiveIntegerField(default=1, verbose_name='等級')),
                ('employment_type', models.CharField(choices=[('full_time', '正社員'), ('part_time', 'パート'), ('contract', '契約社員'), ('dispatch', '派遣社員')], default='full_time', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('personal_email', models.EmailField(blank=True, max_length=254, verbose_name='個人メール')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managers', models.ManyToManyField(blank=True, related_name='subordinates', to='employees.employee', verbose_name='上司')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '社員情報',
                'verbose_name_plural': '社員情報',
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('relationship', models.CharField(max_length=50, verbose_name='続柄')),
                ('phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employees.employee')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('relationship', models.CharField(choices=[('spouse', '配偶者'), ('child', '子'), ('parent', '親'), ('sibling', '兄弟姉妹'), ('other', 'その他')], max_length=20, verbose_name='続柄')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('is_dependent', models.BooleanField(default=False, verbose_name='扶養家族')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='employees.employee')),
            ],
            options={
                'verbose_name': '家族構成',
            },
        ),
    ]
