# Generated by Django 5.0.4 on 2026-04-10 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100, verbose_name='スキル名')),
                ('category', models.CharField(choices=[('language', 'プログラミング言語'), ('framework', 'フレームワーク'), ('infra', 'インフラ'), ('management', 'マネジメント'), ('lang_spoken', '語学'), ('certificate', '資格'), ('other', 'その他')], max_length=20)),
                ('level', models.PositiveIntegerField(default=1, verbose_name='レベル（1〜5）')),
                ('certified_date', models.DateField(blank=True, null=True, verbose_name='取得日')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有効期限')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='employees.employee')),
            ],
            options={
                'verbose_name': 'スキル',
                'ordering': ['category', 'skill_name'],
            },
        ),
    ]
