# Generated by Django 5.0.4 on 2026-04-10 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='手当名')),
                ('allowance_type', models.CharField(choices=[('housing', '住宅手当'), ('secondment', '出向手当'), ('technical', '技術手当'), ('commute', '通勤手当'), ('other', 'その他手当')], max_length=20)),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='金額（円）')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '手当マスタ',
            },
        ),
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.PositiveIntegerField(unique=True, verbose_name='等級')),
                ('base_salary', models.PositiveIntegerField(verbose_name='基本給（円）')),
                ('valid_from', models.DateField(verbose_name='適用開始日')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='適用終了日')),
            ],
            options={
                'verbose_name': '給与等級マスタ',
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='個別金額（空欄=マスタ金額使用）')),
                ('valid_from', models.DateField(verbose_name='適用開始日')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='適用終了日')),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.allowance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='employees.employee')),
            ],
            options={
                'verbose_name': '社員手当',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(verbose_name='年')),
                ('month', models.PositiveIntegerField(verbose_name='月')),
                ('base_salary', models.PositiveIntegerField(default=0, verbose_name='基本給')),
                ('total_allowances', models.PositiveIntegerField(default=0, verbose_name='手当合計')),
                ('overtime_pay', models.PositiveIntegerField(default=0, verbose_name='残業手当')),
                ('gross_salary', models.PositiveIntegerField(default=0, verbose_name='支給合計')),
                ('health_insurance', models.PositiveIntegerField(default=0, verbose_name='健康保険料')),
                ('pension', models.PositiveIntegerField(default=0, verbose_name='厚生年金')),
                ('employment_insurance', models.PositiveIntegerField(default=0, verbose_name='雇用保険料')),
                ('income_tax', models.PositiveIntegerField(default=0, verbose_name='所得税')),
                ('resident_tax', models.PositiveIntegerField(default=0, verbose_name='住民税')),
                ('total_deductions', models.PositiveIntegerField(default=0, verbose_name='控除合計')),
                ('net_salary', models.PositiveIntegerField(default=0, verbose_name='差引支給額')),
                ('status', models.CharField(choices=[('draft', '計算中'), ('confirmed', '確定済')], default='draft', max_length=20)),
                ('payslip_url', models.URLField(blank=True, verbose_name='PDF URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
            ],
            options={
                'verbose_name': '給与明細',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
