# Generated by Django 5.0.4 on 2026-04-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_softdelete_fields'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='onboardingassignment',
            name='unique_onboarding_assignment',
        ),
        migrations.RemoveConstraint(
            model_name='onboardingtaskitem',
            name='unique_onboarding_task_item',
        ),
        migrations.AlterUniqueTogether(
            name='onboardingassignment',
            unique_together={('template', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='onboardingtaskitem',
            unique_together={('assignment', 'template_task')},
        ),
    ]
