# Generated by Django 5.0.4 on 2026-04-10 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='科目コード')),
                ('name', models.CharField(max_length=100, verbose_name='科目名')),
                ('category', models.CharField(choices=[('travel', '旅費交通費'), ('supplies', '消耗品費'), ('entertainment', '接待交際費'), ('communication', '通信費'), ('other', 'その他')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '勘定科目',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(choices=[('transportation', '交通費'), ('general', '一般経費')], max_length=20)),
                ('amount', models.PositiveIntegerField(verbose_name='金額（円）')),
                ('expense_date', models.DateField(verbose_name='費用発生日')),
                ('description', models.TextField(verbose_name='内容説明')),
                ('receipt_url', models.URLField(blank=True, verbose_name='領収書URL（S3）')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済'), ('rejected', '却下'), ('settled', '精算済')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expense.accountitem')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_requests', to='employees.employee')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_approvals', to='employees.employee')),
            ],
            options={
                'verbose_name': '経費申請',
                'ordering': ['-created_at'],
            },
        ),
    ]
