# Generated by Django 5.0.4 on 2026-04-10 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('annual', '有給休暇'), ('special', '特別休暇'), ('sick', '病気休暇'), ('maternity', '産休'), ('childcare', '育休'), ('bereavement', '忌引き')], max_length=20, verbose_name='休暇種別')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('days', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='日数')),
                ('reason', models.TextField(blank=True, verbose_name='理由')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済'), ('rejected', '却下'), ('cancelled', '取消')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
            ],
            options={
                'verbose_name': '休暇申請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.PositiveIntegerField(verbose_name='年度')),
                ('granted_days', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='付与日数')),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='使用日数')),
                ('carried_days', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='繰越日数')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
            ],
            options={
                'verbose_name': '有給残日数',
                'unique_together': {('employee', 'fiscal_year')},
            },
        ),
    ]
