# Generated by Django 5.0.4 on 2026-04-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_sync', '0002_alter_usercalendartoken_deleted_by_and_more'),
        ('calendar_sync', '0002_calendarevent'),
    ]

    operations = [
    ]
