# Generated by Django 5.0.4 on 2026-04-29 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_sync', '0003_merge_20260429_1054'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_sy_user_id_8f4267_idx',
            old_name='calendar_sy_user_id_start_d_idx',
        ),
    ]
